#!/bin/bash

docker build \
  --build-arg DEBUG_BUILD=1 \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  -f "${DOCKERFILE_PATH}" \
  -t "${IMAGE_NAME}" .